"""Rename region_detail to regionDetail

Revision ID: 562a5c188db7
Revises: 9283874b0393
Create Date: 2024-12-29 14:53:59.235872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '562a5c188db7'
down_revision = '9283874b0393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regionDetail', sa.String(length=255), nullable=True))
        batch_op.drop_column('region_detail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_detail', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('regionDetail')

    # ### end Alembic commands ###
