"""Added missing columns

Revision ID: 59c76f141529
Revises: 562a5c188db7
Create Date: 2025-01-09 20:41:01.830351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59c76f141529'
down_revision = '562a5c188db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_column('regionDetail')

    with op.batch_alter_table('top_episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.Date(), nullable=False))
        batch_op.create_unique_constraint('uq_top_episode', ['date_id', 'region_id', 'episode_uri'])
        batch_op.create_foreign_key(None, 'date', ['date_id'], ['date'])

    with op.batch_alter_table('top_podcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.Date(), nullable=False))
        batch_op.create_unique_constraint('uq_top_podcast', ['date_id', 'region_id', 'podcast_uri'])
        batch_op.create_foreign_key(None, 'date', ['date_id'], ['date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_podcasts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_top_podcast', type_='unique')
        batch_op.drop_column('date_id')

    with op.batch_alter_table('top_episodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_top_episode', type_='unique')
        batch_op.drop_column('date_id')

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regionDetail', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
