"""Add region_detail to Region Model

Revision ID: 9283874b0393
Revises: 
Create Date: 2024-12-29 14:33:40.525473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9283874b0393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_detail', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_column('region_detail')

    # ### end Alembic commands ###
